columns:
  - BIOMASS: float64
  - NUCLEAR: float64
  - SOLAR: float64
  - WIND_ONSHORE: float64
  - consommation_totale: float64
  - temp: float64

numeric_columns:
  - BIOMASS
  - NUCLEAR
  - SOLAR
  - WIND_ONSHORE
  - consommation_totale
  - temp