name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      registry: ${{ steps.login-ecr.outputs.registry }}
      repository: ${{ secrets.ECR_REPOSITORY_NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          # Build a docker container and push it to ECR
          
          # Trim whitespace from variables
          ECR_REGISTRY=$(echo "$ECR_REGISTRY" | xargs)
          ECR_REPOSITORY=$(echo "$ECR_REPOSITORY" | xargs)
          IMAGE_TAG=$(echo "$IMAGE_TAG" | xargs)
          
          echo "Building Docker image..."
          echo "ECR_REGISTRY: '$ECR_REGISTRY'"
          echo "ECR_REPOSITORY: '$ECR_REPOSITORY'"
          echo "IMAGE_TAG: '$IMAGE_TAG'"
          
          # Verify that environment variables are set
          if [ -z "$ECR_REGISTRY" ]; then
            echo "Error: ECR_REGISTRY is not set or empty"
            exit 1
          fi
          
          if [ -z "$ECR_REPOSITORY" ]; then
            echo "Error: ECR_REPOSITORY is not set or empty"
            echo "Please check that the secret ECR_REPOSITORY_NAME is properly configured in GitHub"
            exit 1
          fi
          
          # Validate ECR repository name format
          if ! echo "$ECR_REPOSITORY" | grep -qE '^[a-z0-9][a-z0-9_/-]*$'; then
            echo "Error: ECR_REPOSITORY contains invalid characters: '$ECR_REPOSITORY'"
            echo "ECR repository names must be lowercase and can only contain alphanumeric characters, hyphens, underscores, and forward slashes"
            exit 1
          fi
          
          # Construct the full image name
          FULL_IMAGE_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          echo "Full image name: '$FULL_IMAGE_NAME'"
          
          # Build Docker image
          echo "Building Docker image..."
          docker build -t "${FULL_IMAGE_NAME}" .
          
          # Push image to ECR
          echo "Pushing image to ECR..."
          docker push "${FULL_IMAGE_NAME}"
          
          # Set output for next steps
          echo "image=${FULL_IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "Setting output: image=${FULL_IMAGE_NAME}"

  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Validate and construct image name
        run: |
          # Récupérer les outputs du job précédent
          REGISTRY="${{ needs.build-and-push-ecr-image.outputs.registry }}"
          REPOSITORY="${{ needs.build-and-push-ecr-image.outputs.repository }}"
          IMAGE_FROM_OUTPUT="${{ needs.build-and-push-ecr-image.outputs.image }}"
          
          echo "Registry: '$REGISTRY'"
          echo "Repository: '$REPOSITORY'"
          echo "Image from output: '$IMAGE_FROM_OUTPUT'"
          
          # Si l'output existe, l'utiliser, sinon construire l'image
          if [ -n "$IMAGE_FROM_OUTPUT" ]; then
            IMAGE_NAME="$IMAGE_FROM_OUTPUT"
            echo "Using image from output: $IMAGE_NAME"
          else
            # Construire le nom de l'image manuellement
            if [ -z "$REGISTRY" ] || [ -z "$REPOSITORY" ]; then
              echo "Error: Registry or Repository is empty"
              echo "Registry: '$REGISTRY'"
              echo "Repository: '$REPOSITORY'"
              exit 1
            fi
            IMAGE_NAME="${REGISTRY}/${REPOSITORY}:latest"
            echo "Constructed image name: $IMAGE_NAME"
          fi
          
          # Sauvegarder dans les variables d'environnement pour les étapes suivantes
          echo "FINAL_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "Final image to use: $IMAGE_NAME"
      
      - name: Pull latest images
        run: |
          docker pull "$FINAL_IMAGE_NAME"
         
      - name: Stop and remove container if running
        run: |
          if docker ps -q --filter "name=networksecurity" | grep -q .; then
            echo "Stopping existing container..."
            docker stop networksecurity
            docker rm -f networksecurity
          else
            echo "No existing container to stop"
          fi
       
      - name: Run Docker Image to serve users
        run: |
          docker run -d -p 8080:8080 \
            --ipc="host" \
            --name=networksecurity \
            -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e "AWS_REGION=${{ secrets.AWS_REGION }}" \
            "$FINAL_IMAGE_NAME"
            
      - name: Clean previous images and containers
        run: |
          docker system prune -f