name: Deploy to Heroku

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Procfile.dashboard'
      - 'Dockerfile.dashboard'
      - 'heroku.dashboard.yml'
      - 'github/workflows/deploy-dashboard.yml'
      - 'heroku.yml'
      - '.dockerignore'
      - 'images/**'
      - 'notebook/**'

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-deploy:
    name: Continuous Delivery and Deployment
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Set Heroku Stack to Container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Set Heroku Config Vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku config:set \
            URL_TOKEN="${{ secrets.URL_TOKEN }}" \
            CLIENT_ID="${{ secrets.CLIENT_ID }}" \
            CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
            BASE_URL_CONSO="${{ secrets.BASE_URL_CONSO }}" \
            CLIENT_ID_2="${{ secrets.CLIENT_ID_2 }}" \
            CLIENT_SECRET_2="${{ secrets.CLIENT_SECRET_2 }}" \
            BASE_URL_PROD="${{ secrets.BASE_URL_PROD }}" \
            LON="${{ secrets.LON }}" \
            LAT="${{ secrets.LAT }}" \
            --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          dockerfile: Dockerfile
          docker_heroku_process_type: web
          docker_build_args: |
            --no-cache